[package]
name = "gym-shcedule"
version = "0.1.0"
authors = ["BoudBoud47 <mehdi.boudart@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.9"
listenfd = "0.3"
