version: '3'
services:
  backend:
    container_name: rust-api
    image: boud/gym2
    networks:
      - back-network
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@postgres-gym-schedule/gym-schedule
    #command: ["./wait-for-it.sh", "db:5432"]
    restart: unless-stopped
  database:
    image: postgres
    container_name: postgres-gym-schedule
    environment:
      - POSTGRES_DB=gym-schedule
    ports:
      - "5432:5432"
    networks:
      - back-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  back-network: